# Production frontend build
FROM node:20-alpine AS build

WORKDIR /app
ARG VITE_BACKEND_URL=http://127.0.0.1:8000
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine AS production
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
