"""geography and facility metadata

Revision ID: 055d9893619c
Revises: 3858a5560740
Create Date: 2026-09-30 13:15:09.947985+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055d9893619c'
down_revision: Union[str, None] = '3858a5560740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('states',
    sa.Column('country_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'code')
    )
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_states_country_id'), ['country_id'], unique=False)

    op.create_table('districts',
    sa.Column('state_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_id', 'code')
    )
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_districts_state_id'), ['state_id'], unique=False)

    op.create_table('blocks',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'code')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocks_district_id'), ['district_id'], unique=False)

    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_type', sa.String(length=30), server_default='phc', nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('block_id', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('source_device', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_facilities_block_id'), ['block_id'], unique=False)
        batch_op.create_foreign_key('fk_facilities_block', 'blocks', ['block_id'], ['id'])
        batch_op.create_check_constraint('ck_facility_latitude', 'latitude BETWEEN -90 AND 90')
        batch_op.create_check_constraint('ck_facility_longitude', 'longitude BETWEEN -180 AND 180')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint('ck_facility_latitude', type_='check')
        batch_op.drop_constraint('ck_facility_longitude', type_='check')
        batch_op.drop_constraint('fk_facilities_block', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_facilities_block_id'))
        batch_op.drop_column('source_device')
        batch_op.drop_column('version')
        batch_op.drop_column('contact')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('block_id')
        batch_op.drop_column('address')
        batch_op.drop_column('facility_type')

    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocks_district_id'))

    op.drop_table('blocks')
    with op.batch_alter_table('districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_districts_state_id'))

    op.drop_table('districts')
    with op.batch_alter_table('states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_states_country_id'))

    op.drop_table('states')
    op.drop_table('countries')
    # ### end Alembic commands ###

