"""integration provenance recommendations barcodes backups

Revision ID: 0d743597d6d7
Revises: e2a99ffbc9e2
Create Date: 2026-09-30 13:43:57.334542+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d743597d6d7'
down_revision: Union[str, None] = 'e2a99ffbc9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('artifact_key', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artifact_key')
    )
    op.create_table('barcodes',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(medicine_id IS NULL) <> (batch_id IS NULL)'),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('population_snapshots',
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('population >= 0'),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('population_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_population_snapshots_district_id'), ['district_id'], unique=False)

    op.create_table('weather_cache',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id')
    )
    op.create_table('optimization_recommendations',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('transfer_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_recommendations_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_optimization_recommendations_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimization_recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimization_recommendations_source_id'))
        batch_op.drop_index(batch_op.f('ix_optimization_recommendations_destination_id'))

    op.drop_table('optimization_recommendations')
    op.drop_table('weather_cache')
    with op.batch_alter_table('population_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_population_snapshots_district_id'))

    op.drop_table('population_snapshots')
    op.drop_table('barcodes')
    op.drop_table('backup_records')
    # ### end Alembic commands ###
