"""stock policies recalls and mutation receipts

Revision ID: 63636eb79d4f
Revises: 055d9893619c
Create Date: 2026-09-30 13:18:57.859440+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63636eb79d4f'
down_revision: Union[str, None] = '055d9893619c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mutation_receipts',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'operation', 'key')
    )
    op.create_table('recall_records',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('initiated_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('resolution', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recall_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recall_records_batch_id'), ['batch_id'], unique=False)

    op.create_table('stock_policies',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('critical_days', sa.Double(), nullable=False),
    sa.Column('low_days', sa.Double(), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('minimum_history_days', sa.Integer(), nullable=False),
    sa.Column('expiry_warning_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('critical_days >= 0 AND low_days >= critical_days'),
    sa.CheckConstraint('lead_days >= 0 AND safety_stock >= 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'medicine_id')
    )
    with op.batch_alter_table('stock_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_policies_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_policies_medicine_id'), ['medicine_id'], unique=False)

    op.create_table('expiry_records',
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['medicine_inventory.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['stock_transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    with op.batch_alter_table('expiry_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expiry_records_inventory_id'), ['inventory_id'], unique=False)

    with op.batch_alter_table('medicine_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reserved', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medicine_inventory', schema=None) as batch_op:
        batch_op.drop_column('reserved')

    with op.batch_alter_table('expiry_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expiry_records_inventory_id'))

    op.drop_table('expiry_records')
    with op.batch_alter_table('stock_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_policies_medicine_id'))
        batch_op.drop_index(batch_op.f('ix_stock_policies_facility_id'))

    op.drop_table('stock_policies')
    with op.batch_alter_table('recall_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recall_records_batch_id'))

    op.drop_table('recall_records')
    op.drop_table('mutation_receipts')
    # ### end Alembic commands ###
