"""district permission scope

Revision ID: 9085fbb5b8c2
Revises: 61a1f12dca10
Create Date: 2026-09-30 13:49:59.799187+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9085fbb5b8c2'
down_revision: Union[str, None] = '61a1f12dca10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_districts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'district_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_districts')
    # ### end Alembic commands ###
