"""transfer approval reservation and tracking

Revision ID: 9f69c6ee117a
Revises: 63636eb79d4f
Create Date: 2026-09-30 13:21:15.834903+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f69c6ee117a'
down_revision: Union[str, None] = '63636eb79d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_requests',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_id <> destination_id'),
    sa.ForeignKeyConstraint(['destination_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_requests_destination_id'), ['destination_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfer_requests_source_id'), ['source_id'], unique=False)

    op.create_table('transfer_approvals',
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_approvals_transfer_id'), ['transfer_id'], unique=False)

    op.create_table('transfer_items',
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0'),
    sa.ForeignKeyConstraint(['batch_id'], ['medicine_batches.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_id', 'batch_id')
    )
    with op.batch_alter_table('transfer_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_items_transfer_id'), ['transfer_id'], unique=False)

    op.create_table('transfer_tracking',
    sa.Column('transfer_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_tracking_transfer_id'), ['transfer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_tracking_transfer_id'))

    op.drop_table('transfer_tracking')
    with op.batch_alter_table('transfer_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_items_transfer_id'))

    op.drop_table('transfer_items')
    with op.batch_alter_table('transfer_approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_approvals_transfer_id'))

    op.drop_table('transfer_approvals')
    with op.batch_alter_table('transfer_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_requests_source_id'))
        batch_op.drop_index(batch_op.f('ix_transfer_requests_destination_id'))

    op.drop_table('transfer_requests')
    # ### end Alembic commands ###
