"""cold chain beds workforce and aggregates

Revision ID: b0162db94c57
Revises: b9076339868f
Create Date: 2026-09-30 13:28:05.835240+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0162db94c57'
down_revision: Union[str, None] = 'b9076339868f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bed_capacity',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('bed_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupied', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('capacity >= 0 AND occupied >= 0 AND occupied <= capacity'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'bed_type')
    )
    with op.batch_alter_table('bed_capacity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bed_capacity_facility_id'), ['facility_id'], unique=False)

    op.create_table('disease_counts',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_device', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('count >= 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'day', 'category')
    )
    with op.batch_alter_table('disease_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disease_counts_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_disease_counts_facility_id'), ['facility_id'], unique=False)

    op.create_table('patient_footfall_aggregates',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('source_device', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('count >= 0'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'day', 'category')
    )
    with op.batch_alter_table('patient_footfall_aggregates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_footfall_aggregates_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_footfall_aggregates_facility_id'), ['facility_id'], unique=False)

    op.create_table('staff',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('staff_role_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['staff_role_id'], ['staff_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_facility_id'), ['facility_id'], unique=False)

    op.create_table('attendance',
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'day')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_staff_id'), ['staff_id'], unique=False)

    op.create_table('bed_occupancy_history',
    sa.Column('bed_id', sa.Uuid(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupied', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bed_id'], ['bed_capacity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bed_occupancy_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bed_occupancy_history_bed_id'), ['bed_id'], unique=False)

    op.create_table('shifts',
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('ends_at > starts_at'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_staff_id'), ['staff_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shifts_starts_at'), ['starts_at'], unique=False)

    op.create_table('temperature_observations',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('shipment_id', sa.Uuid(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Double(), nullable=False),
    sa.Column('minimum', sa.Double(), nullable=False),
    sa.Column('maximum', sa.Double(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('excursion', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('minimum < maximum'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id')
    )
    with op.batch_alter_table('temperature_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temperature_observations_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temperature_observations_observed_at'), ['observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temperature_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temperature_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_temperature_observations_facility_id'))

    op.drop_table('temperature_observations')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_starts_at'))
        batch_op.drop_index(batch_op.f('ix_shifts_staff_id'))
        batch_op.drop_index(batch_op.f('ix_shifts_facility_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('bed_occupancy_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bed_occupancy_history_bed_id'))

    op.drop_table('bed_occupancy_history')
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_staff_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_facility_id'))

    op.drop_table('attendance')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_facility_id'))

    op.drop_table('staff')
    with op.batch_alter_table('patient_footfall_aggregates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_footfall_aggregates_facility_id'))
        batch_op.drop_index(batch_op.f('ix_patient_footfall_aggregates_day'))

    op.drop_table('patient_footfall_aggregates')
    with op.batch_alter_table('disease_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disease_counts_facility_id'))
        batch_op.drop_index(batch_op.f('ix_disease_counts_day'))

    op.drop_table('disease_counts')
    with op.batch_alter_table('bed_capacity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bed_capacity_facility_id'))

    op.drop_table('bed_capacity')
    op.drop_table('staff_roles')
    # ### end Alembic commands ###
