"""suppliers warehouses procurement shipments

Revision ID: b9076339868f
Revises: 9f69c6ee117a
Create Date: 2026-09-30 13:24:57.173254+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9076339868f'
down_revision: Union[str, None] = '9f69c6ee117a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('lead_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('purchase_orders',
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('warehouses',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('capacity', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id')
    )
    op.create_table('procurement_history',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procurement_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_procurement_history_order_id'), ['order_id'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('received', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0 AND received >= 0 AND received <= quantity'),
    sa.CheckConstraint('unit_price >= 0'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'medicine_id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_order_id'), ['order_id'], unique=False)

    op.create_table('shipments',
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=False),
    sa.Column('transport', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(order_id IS NULL) <> (transfer_id IS NULL)'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['transfer_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipments_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shipments_transfer_id'), ['transfer_id'], unique=False)

    op.create_table('warehouse_inventory',
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('inventory_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['medicine_inventory.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inventory_id')
    )
    with op.batch_alter_table('warehouse_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('shipment_history',
    sa.Column('shipment_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shipment_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shipment_history_shipment_id'), ['shipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipment_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipment_history_shipment_id'))

    op.drop_table('shipment_history')
    with op.batch_alter_table('warehouse_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_warehouse_id'))

    op.drop_table('warehouse_inventory')
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shipments_transfer_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_order_id'))
        batch_op.drop_index(batch_op.f('ix_shipments_facility_id'))

    op.drop_table('shipments')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_order_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('procurement_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_procurement_history_order_id'))

    op.drop_table('procurement_history')
    op.drop_table('warehouses')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_facility_id'))

    op.drop_table('purchase_orders')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
