"""equipment maintenance ambulance availability

Revision ID: e2a99ffbc9e2
Revises: b2a06a4035a1
Create Date: 2026-09-30 13:34:52.348332+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a99ffbc9e2'
down_revision: Union[str, None] = 'b2a06a4035a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_records',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('operational', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    with op.batch_alter_table('ambulance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambulance_records_facility_id'), ['facility_id'], unique=False)

    op.create_table('equipment',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('equipment_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_maintenance', sa.Date(), nullable=True),
    sa.Column('next_maintenance', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_next_maintenance'), ['next_maintenance'], unique=False)

    op.create_table('maintenance_records',
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('performed_on', sa.Date(), nullable=False),
    sa.Column('next_due', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_records_equipment_id'), ['equipment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_records_equipment_id'))

    op.drop_table('maintenance_records')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_next_maintenance'))
        batch_op.drop_index(batch_op.f('ix_equipment_facility_id'))

    op.drop_table('equipment')
    with op.batch_alter_table('ambulance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambulance_records_facility_id'))

    op.drop_table('ambulance_records')
    # ### end Alembic commands ###
